<a href="https://colab.research.google.com/github/pavanKarthik2006/Biocomputing/blob/main/Classification_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
text_data=['A metaverse is a network of 3D virtual worlds focused on social connection.',
           'In futurism and science fiction, the term is often described as a hypothetical iteration of the Internet as a single',
           'universal virtual world that is facilitated by the use of virtual and augmented reality headsets.',
           'The term "metaverse" has its origins  the 1992 science fiction novel Snow Crash as a portmanteau of "meta" and "universe."',
           'Various metaverses have been developed for popular use such as virtual world platforms like Second Life.',
           'Some metaverse iterations involve integration between virtual and physical spaces and virtual economies',
           'often including a significant interest in advancing virtual reality technology.',
           'The term has seen considerable use as a buzzword for public relations purposes to exaggerate development progress for various related technologies and projects.[10] Information privacy and user addiction are concerns within metaverses',
           'stemming from challenges facing the social media and video game industries as a whole.']

vectorizer=CountVectorizer()

X=vectorizer.fit_transform(text_data)
X.shape

token_index=vectorizer.vocabulary_.get("metaverse")
print(token_index)

51


In [5]:
new_vectorizer=CountVectorizer(min_df=2)
X=vectorizer.fit_transform(text_data)
X.shape

(9, 99)

In [8]:
from sklearn.feature_extraction.text  import CountVectorizer

Docs = [
    'This is the first question.',
    'This document is the second document.',
    'And this is the third one'
]

vectorizer=CountVectorizer(max_features=10)
X=vectorizer.fit_transform(Docs).toarray()

print(X)

[[0 0 1 1 0 1 0 1 0 1]
 [0 2 0 1 0 0 1 1 0 1]
 [1 0 0 1 1 0 0 1 1 1]]


In [9]:
import numpy as np
from sklearn.neighbors import NearestNeighbors

def k_closest(X, p, k):
    model = NearestNeighbors(n_neighbors=k)
    model.fit(X)
    distances, indices = model.kneighbors(p)
    return X[indices[0]]

X = np.asarray([[72, 69, 82], [9, 79, 99], [20, 47, 88], [80, 64, 49]])
p = np.asarray([[0, 0, 0]])
k = 1

result = k_closest(X, p, k)
print(result)

[[20 47 88]]


In [10]:
import numpy as np

def distance(x0: np.array, X: np.ndarray, p: int = 2):
    distances = []
    for x in X:
        total = 0
        for i in range(len(x0)):
            total += abs(x0[i] - x[i]) ** p
        d = total ** (1 / p)
        distances.append(d)
    return distances

In [11]:
x0 = np.array([1, 0, 0, 0])
X = np.asarray([[1, 0, 0, 0], [0, 1, 1, 1], [1, 2, 0, 0]])
p = 2

print(distance(x0, X, p))

[np.float64(0.0), np.float64(2.0), np.float64(2.0)]


In [18]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


digits=load_digits()
X,y=digits.data,digits.target

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=10)

scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.fit_transform(X_test)

model=LogisticRegression(multi_class='multinomial',solver='sag',max_iter=1000)
model.fit(X_train_scaled,y_train)

y_pred=model.predict(X_test_scaled)
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


0.9666666666666667


In [20]:
digits.data.shape

(1797, 64)

In [22]:
len(set(digits.target))

10

In [24]:
label_7_count=(digits.target==7).sum()
print(label_7_count)

179


In [26]:
from sklearn.metrics import f1_score

f1=f1_score(y_test,y_pred,average='weighted')
print(f1)

0.9668475726567656
